### PR TITLE
Alaro surfex

### PR DESCRIPTION
**Pull request by ddegrauwe**
Adding a test for an ALARO+SURFEX forecast.

Necessary data files are on ECMWF ATOS:
- namelist files and PGD file: /home/cv9/.vortexrc/hack/uget/cv9/data/
- geometry file: /home/cv9/.vortexrc/geometries.ini
- LBC files and initial SURFEX file: /hpcperm/cv9/data/alaro_sfx

### CODE REVIEW

**Comment by AlexandreMary** [comment]
Hi Daan,
I merged that, but as I told you last week, the test fails in CY49T2, so I commented it out in `standalone_forecasts.py`

Can you have a look and fix it ?
I don't think it's a big issue, probably linked to changes in the initialization of aerosols, introduced in [this PR](https://github.com/ACCORD-NWP/IAL/pull/169), and that is incomplete in the case of ALARO ?

To run these new tests:
`davai-new_xp -v DV49T2_dev CY49T2`
and then you will have to decomment (and while in debugging mode, comment other tests and remove SP flavour in config file, to go faster)

Thanks
Alexandre

**Comment by ddegrauwe** [comment]
Hi Alexandre,

I solved the crash related to aerosols, but now the forecast fails due to a missing surfex field (SEAICE_SCHEME) in the initial surface file. Is it necessary to regenerate the initial surface file (and PGD file?) when moving from cy48t3 to 49t2?

**Comment by AlexandreMary** [comment]
Hi Daan,
yes that's a consequence from the common SURFEX version entered in CY49T1, you need to regenerate the initial surface file at least, and ideally the PGD at the same time (always good to regenerate PGD with a new version of SURFEX, by experience...)

**Comment by ddegrauwe** [comment]
Hi Alexandre,

I recreated initial files and pgd file, and made a new pull request to DAVAI-tests. Also made a pull request to IAL with the fix for unassociated NSV which made ALARO+SFX crash.

**Pull request merged**
